# Alacritty configuration

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.95

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 24

[general]
#import = ["~/.config/alacritty/tokyonight_storm-folke.toml"]
import = ["~/.config/alacritty/tokyonight_storm-zatchheems.toml"]
